spring.application.name=demand

# H2 Database Connection Settings
spring.datasource.url=jdbc:h2:mem:smart_ride_db;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Web Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA and Hibernate Options
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt-secret = 1aceee991cf342df329d85cfd40979364054f210e3ab328d4b3b6dbcbf4c33f4
app.jet-expiration-milliseconds=604800000
