spring.application.name=demand

# ? Direct Supabase PostgreSQL Live Database Connection
spring.datasource.url=jdbc:postgresql://db.wlvjogfsgjsusgfljwmh.supabase.co:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver

# Keep username strictly as postgres
spring.datasource.username=postgres
# Paste your original project password here:
spring.datasource.password=1OTttIBaMIV5yhxe

# JPA Engine Target Configuration Options
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Security Configurations Keys
app.jwt-secret=1aceee991cf342df329d85cfd40979364054f210e3ab328d4b3b6dbcbf4c33f4
app.jwt-expiration-milliseconds=604800000